// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEgrBlK84399u-8DbyeQmHS9knaudH3eE',
    appId: '1:144457547920:web:f711666e6e55ba2bb51815',
    messagingSenderId: '144457547920',
    projectId: 'latihan-uts-26c91',
    authDomain: 'latihan-uts-26c91.firebaseapp.com',
    databaseURL: 'https://latihan-uts-26c91-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-uts-26c91.firebasestorage.app',
    measurementId: 'G-MG3GV58R1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM26pBc2gLRr5dBB1dGoyMzHryOYAyncg',
    appId: '1:144457547920:android:56a20c2511280c53b51815',
    messagingSenderId: '144457547920',
    projectId: 'latihan-uts-26c91',
    databaseURL: 'https://latihan-uts-26c91-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-uts-26c91.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEgrBlK84399u-8DbyeQmHS9knaudH3eE',
    appId: '1:144457547920:web:f88891780b08b109b51815',
    messagingSenderId: '144457547920',
    projectId: 'latihan-uts-26c91',
    authDomain: 'latihan-uts-26c91.firebaseapp.com',
    databaseURL: 'https://latihan-uts-26c91-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-uts-26c91.firebasestorage.app',
    measurementId: 'G-WGCVGFQXXD',
  );
}
